tup = (1,2,3,4,"raghav" , 3.14)
print(tup)
print(tup[0])
print(tup[1])
print(tup[2])
print(tup[3])
print(tup[4])
print(tup[5])
print("total length is", len(tup))
print(tup.count(1))
print(tup.index(2))
